export enum Level {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}

export enum CourseStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
}

export enum CourseCategory {
  // Development
  WEB_DEVELOPMENT = 'WEB DEVELOPMENT',
  MOBILE_DEVELOPMENT = 'MOBILE DEVELOPMENT',
  GAME_DEVELOPMENT = 'GAME DEVELOPMENT',
  SOFTWARE_ENGINEERING = 'SOFTWARE ENGINEERING',
  DATA_SCIENCE = 'DATA SCIENCE',
  AI_MACHINE_LEARNING = 'AI MACHINE LEARNING',
  CYBERSECURITY = 'CYBERSECURITY',
  DEVOPS_CLOUD = 'DEVOPS CLOUD',
  PROGRAMMING = 'PROGRAMMING',

  // IT & Software
  NETWORKING_SECURITY = 'NETWORKING SECURITY',
  IT_CERTIFICATIONS = 'IT CERTIFICATIONS',
  OPERATING_SYSTEMS = 'OPERATING SYSTEMS',
  BLOCKCHAIN_WEB3 = 'BLOCKCHAIN WEB3',
  DATABASE_MANAGEMENT = 'DATABASE MANAGEMENT',

  // Business
  ENTREPRENEURSHIP = 'ENTREPRENEURSHIP',
  DIGITAL_MARKETING = 'DIGITAL MARKETING',
  FINANCE_INVESTING = 'FINANCE INVESTING',
  PROJECT_MANAGEMENT = 'PROJECT MANAGEMENT',
  LEADERSHIP_MANAGEMENT = 'LEADERSHIP MANAGEMENT',
  SALES_NEGOTIATION = 'SALES NEGOTIATION',

  // Design
  GRAPHIC_DESIGN = 'GRAPHIC DESIGN',
  UI_UX_DESIGN = 'UI UX DESIGN',
  THREE_D_MODELING = '3D MODELING',
  VIDEO_EDITING = 'VIDEO EDITING',

  // Personal Development
  PRODUCTIVITY = 'PRODUCTIVITY',
  PUBLIC_SPEAKING = 'PUBLIC SPEAKING',
  CAREER_DEVELOPMENT = 'CAREER DEVELOPMENT',
  SELF_IMPROVEMENT = 'SELF IMPROVEMENT',

  // Lifestyle
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  MUSIC_PRODUCTION = 'MUSIC PRODUCTION',
  HEALTH_FITNESS = 'HEALTH FITNESS',
  COOKING_NUTRITION = 'COOKING NUTRITION',

  // Academics
  MATHEMATICS = 'MATHEMATICS',
  SCIENCE = 'SCIENCE',
  LANGUAGE_LEARNING = 'LANGUAGE LEARNING',
  HISTORY_PHILOSOPHY = 'HISTORY PHILOSOPHY',
}
