export enum Level {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}

export enum CourseStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
}

export enum CourseCategory {
  // Development
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  MOBILE_DEVELOPMENT = 'MOBILE_DEVELOPMENT',
  GAME_DEVELOPMENT = 'GAME_DEVELOPMENT',
  SOFTWARE_ENGINEERING = 'SOFTWARE_ENGINEERING',
  DATA_SCIENCE = 'DATA_SCIENCE',
  AI_MACHINE_LEARNING = 'AI_MACHINE_LEARNING',
  CYBERSECURITY = 'CYBERSECURITY',
  DEVOPS_CLOUD = 'DEVOPS_CLOUD',
  PROGRAMMING = 'PROGRAMMING',

  // IT & Software
  NETWORKING_SECURITY = 'NETWORKING_SECURITY',
  IT_CERTIFICATIONS = 'IT_CERTIFICATIONS',
  OPERATING_SYSTEMS = 'OPERATING_SYSTEMS',
  BLOCKCHAIN_WEB3 = 'BLOCKCHAIN_WEB3',
  DATABASE_MANAGEMENT = 'DATABASE_MANAGEMENT',

  // Business
  ENTREPRENEURSHIP = 'ENTREPRENEURSHIP',
  DIGITAL_MARKETING = 'DIGITAL_MARKETING',
  FINANCE_INVESTING = 'FINANCE_INVESTING',
  PROJECT_MANAGEMENT = 'PROJECT_MANAGEMENT',
  LEADERSHIP_MANAGEMENT = 'LEADERSHIP_MANAGEMENT',
  SALES_NEGOTIATION = 'SALES_NEGOTIATION',

  // Design
  GRAPHIC_DESIGN = 'GRAPHIC_DESIGN',
  UI_UX_DESIGN = 'UI_UX_DESIGN',
  THREE_D_MODELING = 'THREE_D_MODELING',
  VIDEO_EDITING = 'VIDEO_EDITING',

  // Personal Development
  PRODUCTIVITY = 'PRODUCTIVITY',
  PUBLIC_SPEAKING = 'PUBLIC_SPEAKING',
  CAREER_DEVELOPMENT = 'CAREER_DEVELOPMENT',
  SELF_IMPROVEMENT = 'SELF_IMPROVEMENT',

  // Lifestyle
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  MUSIC_PRODUCTION = 'MUSIC_PRODUCTION',
  HEALTH_FITNESS = 'HEALTH_FITNESS',
  COOKING_NUTRITION = 'COOKING_NUTRITION',

  // Academics
  MATHEMATICS = 'MATHEMATICS',
  SCIENCE = 'SCIENCE',
  LANGUAGE_LEARNING = 'LANGUAGE_LEARNING',
  HISTORY_PHILOSOPHY = 'HISTORY_PHILOSOPHY',
}
