package emil.find_course.domains.enums;

public enum CourseCategory {
    // Development
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    GAME_DEVELOPMENT,
    SOFTWARE_ENGINEERING,
    DATA_SCIENCE,
    AI_MACHINE_LEARNING,
    CYBERSECURITY,
    DEVOPS_CLOUD,
    PROGRAMMING,

    // IT & Software
    NETWORKING_SECURITY,
    IT_CERTIFICATIONS,
    OPERATING_SYSTEMS,
    BLOCKCHAIN_WEB3,
    DATABASE_MANAGEMENT,

    // Business
    ENTREPRENEURSHIP,
    DIGITAL_MARKETING,
    FINANCE_INVESTING,
    PROJECT_MANAGEMENT,
    LEADERSHIP_MANAGEMENT,
    SALES_NEGOTIATION,

    // Design
    GRAPHIC_DESIGN,
    UI_UX_DESIGN,
    THREE_D_MODELING,
    VIDEO_EDITING,

    // Personal Development
    PRODUCTIVITY,
    PUBLIC_SPEAKING,
    CAREER_DEVELOPMENT,
    SELF_IMPROVEMENT,

    // Lifestyle
    PHOTOGRAPHY,
    MUSIC_PRODUCTION,
    HEALTH_FITNESS,
    COOKING_NUTRITION,

    // Academics
    MATHEMATICS,
    SCIENCE,
    LANGUAGE_LEARNING,
    HISTORY_PHILOSOPHY;
}